# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
# This setting speeds up running single tasks from subprojects by only configuring what's needed.
# see https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html
# Disabled because this breaks Gradle tasks in older toolchains
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

# JEI
modName=JEIunofficial
modId=jei
modAuthor=StardustMINUS and the Stellar Remnants Team
# http://maven.apache.org/guides/mini/guide-naming-conventions.html
modGroup=mezz.jei
modDescription=An unofficial fork of JustEnoughItems (JEI) for Stellar Remnants. Enhances JEI with several features. Do not install alongside the official JEI. Also available on Modrinth: https://modrinth.com/project/jei-unofficial. Copyright (c) 2014-2015 mezz (MIT), adapted GTNH NotEnoughItems portions (c) 2019-2024 mitchej123 and the GTNH Team (LGPL-3.0-or-later), original additions (c) 2026 StardustMINUS and the Stellar Remnants Team.
# Mojang ships Java 17 to end users in 1.18+
modJavaVersion=17
githubUrl=https://github.com/StardustMINUS-01/JustEnoughItems

# Minecraft
minecraftVersion=1.20.1
minecraftVersionRange=[1.20.1, 1.20.2)
minecraftVersionRangeStart=1.20.1

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
forgeVersion=47.3.1
forgeLoaderVersionRange=[47,)
forgeVersionRange=[47.0,)

# Fabric
# https://fabricmc.net/develop/
fabricLoaderVersion=0.16.3
fabricApiVersion=0.92.2+1.20.1

# AMECS (Fabric only, for keybinds with modifiers)
# https://maven.siphalor.de/de/siphalor/amecsapi-1.20/maven-metadata.xml
amecsMinecraftVersion=1.20
amecsVersionFabric=1.5.3+mc1.20-pre1

# Mappings
# https://parchmentmc.org/docs/getting-started
parchmentMinecraftVersion=1.20.1
parchmentVersionForge=2023.09.03-1.20.1
parchmentVersionFabric=2023.09.03

# Publishing
curseProjectId=1642978
curseHomepageUrl=https://www.curseforge.com/minecraft/mc-mods/jei-unofficial
modrinthId=jei-unofficial
homepageUrl=https://www.curseforge.com/minecraft/mc-mods/jei-unofficial

# Test
jUnitVersion=5.8.2
bakedSubstringIndexVersion=0.1.0
# https://central.sonatype.com/artifact/net.mezzdev/suffixtree
suffixtreeVersion=1.1.0

# Version
specificationVersion=15.48.0
