modLoader="javafml"
loaderVersion="${neoforgeLoaderVersionRange}"
license="MIT AND LGPL-3.0-or-later"

[[mods]]
modId="jeitests"
version="${version}"
displayName="Just Enough Items: Tests"
description='''Tests for Just Enough Items.'''

[[dependencies.jeitests]]
    modId="jei"
    type="required"
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.jeitests]]
    modId="neoforge"
    type="required"
    versionRange="${neoforgeVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.jeitests]]
    modId="minecraft"
    type="required"
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"
