package mezz.jei.common.network;

public enum PacketIdServer implements IPacketId {
	RECIPE_TRANSFER,
	DELETE_ITEM,
	GIVE_ITEM,
	SET_HOTBAR_ITEM,
	CHEAT_PERMISSION_REQUEST,
	RECIPE_TRANSFER_COUNTED,
	RECIPE_TRANSFER_WITH_RESULT,
	RECIPE_TRANSFER_COUNTED_WITH_RESULT,
	PULL_BOOKMARK_ITEMS,
	CRAFTING_GRID_CRAFT,
	FILL_CRAFTING_GRID,
	FAST_PICKUP_ITEM,
	ENCODE_RECIPE_CHAIN_PATTERNS,
	SHARE_BOOKMARK_GROUP,
	SHARE_RECIPE,
	SHARE_INGREDIENT,
	CRAFTING_GRID_CRAFT_WITH_RECIPE;

	public static final PacketIdServer[] VALUES = values();
}
